import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "@/app/providers";
import Header from "@/components/Header";
import {AppRouterCacheProvider} from "@mui/material-nextjs/v15-appRouter";
import {ThemeProvider} from "@mui/material/styles";
import theme from  "@/app/themes/theme"


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` h-screen flex flex-col w-full${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <AppRouterCacheProvider >
          <ThemeProvider theme={theme}>
              <Providers >
                  <div className="flex flex-col w-full  h-screen">
                      <Header/>
                      <main className={"flex-grow "}>
                          {children}
                      </main>
                  </div>
              </Providers>
          </ThemeProvider>
      </AppRouterCacheProvider>
      </body>
    </html>
  );
}
